### ISSUE TITLE
Permissions problems

### ISSUE THREAD

**Issue by 9gigsofram** [tastybento/askyblock#211]
I'm having issues with this plugin and permissions ex when i type /is help, i get "an internal error occured while attempting to perform this command"

and this in the console

> [18:21:39 ERROR]: null
org.bukkit.command.CommandException: Unhandled exception executing command 'is' in plugin ASkyBlock v3.0.0.4
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:46) ~[spigot.jar:git-Spigot-5a40365-b70058a]
        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:141) ~[spigot.jar:git-Spigot-5a40365-b70058a]
        at org.bukkit.craftbukkit.v1_9_R1.CraftServer.dispatchCommand(CraftServer.java:645) ~[spigot.jar:git-Spigot-5a40365-b70058a]
        at net.minecraft.server.v1_9_R1.PlayerConnection.handleCommand(PlayerConnection.java:1350) [spigot.jar:git-Spigot-5a40365-b70058a]
        at net.minecraft.server.v1_9_R1.PlayerConnection.a(PlayerConnection.java:1185) [spigot.jar:git-Spigot-5a40365-b70058a]
        at net.minecraft.server.v1_9_R1.PacketPlayInChat.a(PacketPlayInChat.java:45) [spigot.jar:git-Spigot-5a40365-b70058a]
        at net.minecraft.server.v1_9_R1.PacketPlayInChat.a(PacketPlayInChat.java:1) [spigot.jar:git-Spigot-5a40365-b70058a]
        at net.minecraft.server.v1_9_R1.PlayerConnectionUtils$1.run(SourceFile:13) [spigot.jar:git-Spigot-5a40365-b70058a]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_77]
        at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_77]
        at net.minecraft.server.v1_9_R1.SystemUtils.a(SourceFile:45) [spigot.jar:git-Spigot-5a40365-b70058a]
        at net.minecraft.server.v1_9_R1.MinecraftServer.D(MinecraftServer.java:721) [spigot.jar:git-Spigot-5a40365-b70058a]
        at net.minecraft.server.v1_9_R1.DedicatedServer.D(DedicatedServer.java:400) [spigot.jar:git-Spigot-5a40365-b70058a]
        at net.minecraft.server.v1_9_R1.MinecraftServer.C(MinecraftServer.java:660) [spigot.jar:git-Spigot-5a40365-b70058a]
        at net.minecraft.server.v1_9_R1.MinecraftServer.run(MinecraftServer.java:559) [spigot.jar:git-Spigot-5a40365-b70058a]
        at java.lang.Thread.run(Thread.java:745) [?:1.8.0_77]
Caused by: java.lang.ArrayIndexOutOfBoundsException: 1
        at com.wasteofplastic.askyblock.commands.IslandCmd.onCommand(IslandCmd.java:1523) ~[?:?]
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44) ~[spigot.jar:git-Spigot-5a40365-b70058a]
        ... 15 more

**Comment by tastybento** [comment]
You probably have a malformed askyblock.maxhomes permission. It should be something like askyblock.maxhomes.6
If you have letters or more dots in there it'll error like this. Do /pex user (name) list to check.

**Comment by 9gigsofram** [comment]
That seems to have resolved the issue, I’m having other permissions issues, but i believe that is a bug in pex itself.
