### ISSUE TITLE
1.9.4 update

### ISSUE THREAD

**Issue by renzotom** [tastybento/askyblock#222]
Please, update to 1.9.4 :(
[15:53:50] [Server thread/INFO]: [AcidIsland] Enabling AcidIsland v3.0.0.7
[15:53:50] [Server thread/INFO]: No NMS Handler found for v1_9_R2, falling back to Bukkit API.
[15:53:50] [Server thread/INFO]: [AcidIsland] Loading schematic Originalni () for all players, order 1
[15:53:50] [Server thread/INFO]: No NMS Handler found for v1_9_R2, falling back to Bukkit API.
[15:53:50] [Server thread/INFO]: [AcidIsland] Loading schematic Ostrov z netheritovych cihel (nether.schematic) for all players, order 0
[15:53:50] [Server thread/INFO]: No NMS Handler found for v1_9_R2, falling back to Bukkit API.
[15:53:50] [Server thread/ERROR]: Could not parse item [POTION] in schematic - skipping!
[15:53:50] [Server thread/WARN]: java.lang.IllegalArgumentException: Potion Type is not upgradable
[15:53:50] [Server thread/WARN]: 	at org.apache.commons.lang.Validate.isTrue(Validate.java:136)
[15:53:50] [Server thread/WARN]: 	at org.bukkit.potion.PotionData.<init>(PotionData.java:23)
[15:53:50] [Server thread/WARN]: 	at org.bukkit.potion.Potion.toItemStack(Potion.java:324)
[15:53:50] [Server thread/WARN]: 	at com.wasteofplastic.acidisland.nms.fallback.NMSHandler.setPotion(NMSHandler.java:117)
[15:53:50] [Server thread/WARN]: 	at com.wasteofplastic.acidisland.schematics.IslandBlock.setChest(IslandBlock.java:484)
[15:53:50] [Server thread/WARN]: 	at com.wasteofplastic.acidisland.schematics.Schematic.prePasteSchematic(Schematic.java:1089)
[15:53:50] [Server thread/WARN]: 	at com.wasteofplastic.acidisland.schematics.Schematic.<init>(Schematic.java:610)
[15:53:50] [Server thread/WARN]: 	at com.wasteofplastic.acidisland.commands.IslandCmd.loadSchematics(IslandCmd.java:267)
[15:53:50] [Server thread/WARN]: 	at com.wasteofplastic.acidisland.commands.IslandCmd.<init>(IslandCmd.java:123)
[15:53:50] [Server thread/WARN]: 	at com.wasteofplastic.acidisland.ASkyBlock.onEnable(ASkyBlock.java:326)
[15:53:50] [Server thread/WARN]: 	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:292)
[15:53:50] [Server thread/WARN]: 	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:340)
[15:53:50] [Server thread/WARN]: 	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:405)
[15:53:50] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_9_R2.CraftServer.loadPlugin(CraftServer.java:361)
[15:53:50] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_9_R2.CraftServer.enablePlugins(CraftServer.java:321)
[15:53:50] [Server thread/WARN]: 	at net.minecraft.server.v1_9_R2.DedicatedServer.init(DedicatedServer.java:201)
[15:53:50] [Server thread/WARN]: 	at net.minecraft.server.v1_9_R2.MinecraftServer.run(MinecraftServer.java:532)
[15:53:50] [Server thread/WARN]: 	at java.lang.Thread.run(Thread.java:745)
[15:53:50] [Server thread/ERROR]: Could not parse item [POTION] in schematic - skipping!
[15:53:50] [Server thread/WARN]: java.lang.IllegalArgumentException: Potion Type is not upgradable
[15:53:50] [Server thread/WARN]: 	at org.apache.commons.lang.Validate.isTrue(Validate.java:136)
[15:53:50] [Server thread/WARN]: 	at org.bukkit.potion.PotionData.<init>(PotionData.java:23)
[15:53:50] [Server thread/WARN]: 	at org.bukkit.potion.Potion.toItemStack(Potion.java:324)
[15:53:50] [Server thread/WARN]: 	at com.wasteofplastic.acidisland.nms.fallback.NMSHandler.setPotion(NMSHandler.java:117)
[15:53:50] [Server thread/WARN]: 	at com.wasteofplastic.acidisland.schematics.IslandBlock.setChest(IslandBlock.java:484)
[15:53:50] [Server thread/WARN]: 	at com.wasteofplastic.acidisland.schematics.Schematic.prePasteSchematic(Schematic.java:1089)
[15:53:50] [Server thread/WARN]: 	at com.wasteofplastic.acidisland.schematics.Schematic.<init>(Schematic.java:610)
[15:53:50] [Server thread/WARN]: 	at com.wasteofplastic.acidisland.commands.IslandCmd.loadSchematics(IslandCmd.java:267)
[15:53:50] [Server thread/WARN]: 	at com.wasteofplastic.acidisland.commands.IslandCmd.<init>(IslandCmd.java:123)
[15:53:50] [Server thread/WARN]: 	at com.wasteofplastic.acidisland.ASkyBlock.onEnable(ASkyBlock.java:326)
[15:53:50] [Server thread/WARN]: 	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:292)
[15:53:50] [Server thread/WARN]: 	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:340)
[15:53:50] [Server thread/WARN]: 	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:405)
[15:53:50] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_9_R2.CraftServer.loadPlugin(CraftServer.java:361)
[15:53:50] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_9_R2.CraftServer.enablePlugins(CraftServer.java:321)
[15:53:50] [Server thread/WARN]: 	at net.minecraft.server.v1_9_R2.DedicatedServer.init(DedicatedServer.java:201)
[15:53:50] [Server thread/WARN]: 	at net.minecraft.server.v1_9_R2.MinecraftServer.run(MinecraftServer.java:532)
[15:53:50] [Server thread/WARN]: 	at java.lang.Thread.run(Thread.java:745)
[15:53:50] [Server thread/INFO]: [AcidIsland] Loading schematic Chram (temple.schematic) for all players, order 2
[15:53:50] [Server thread/INFO]: [AcidIsland] Loading offline messages...

**Comment by tastybento** [comment]
Try https://github.com/tastybento/askyblock/releases/tag/3.0.0.8

**Comment by renzotom** [comment]
Please, also on AcidIsland?

**Comment by tastybento** [comment]
http://dev.bukkit.org/media/files/917/736/acidisland.jar

Waiting for Bukkit approval.
