### ISSUE TITLE
NPE in IslandGuard

### ISSUE THREAD

**Issue by tastybento** [tastybento/askyblock#272]
There are a number of times that island is checked in IslandGuard without a null check. This causes NPE's if action happens outside an island boundary.

[22:38:12] [Server thread/ERROR]: Could not pass event EntityDamageByEntityEvent to ASkyBlock v3.0.2
org.bukkit.event.EventException
    at org.bukkit.plugin.EventExecutor$1.execute(EventExecutor.java:46) ~[patched_1.9.4.jar:git-Paper-773]
    at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:78) ~[patched_1.9.4.jar:git-Paper-773]
    at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[patched_1.9.4.jar:git-Paper-773]
    at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:517) [patched_1.9.4.jar:git-Paper-773]
    at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:502) [patched_1.9.4.jar:git-Paper-773]
    at org.bukkit.craftbukkit.v1_9_R2.event.CraftEventFactory.callEvent(CraftEventFactory.java:89) [patched_1.9.4.jar:git-Paper-773]
    at org.bukkit.craftbukkit.v1_9_R2.event.CraftEventFactory.callEntityDamageEvent(CraftEventFactory.java:570) [patched_1.9.4.jar:git-Paper-773]
    at org.bukkit.craftbukkit.v1_9_R2.event.CraftEventFactory.handleEntityDamageEvent(CraftEventFactory.java:479) [patched_1.9.4.jar:git-Paper-773]
    at org.bukkit.craftbukkit.v1_9_R2.event.CraftEventFactory.handleLivingEntityDamageEvent(CraftEventFactory.java:602) [patched_1.9.4.jar:git-Paper-773]
    at net.minecraft.server.v1_9_R2.EntityLiving.damageEntity0(EntityLiving.java:1236) [patched_1.9.4.jar:git-Paper-773]
    at net.minecraft.server.v1_9_R2.EntityLiving.damageEntity(EntityLiving.java:843) [patched_1.9.4.jar:git-Paper-773]
    at net.minecraft.server.v1_9_R2.EntityMonster.damageEntity(EntityMonster.java:44) [patched_1.9.4.jar:git-Paper-773]
    at net.minecraft.server.v1_9_R2.EntityHuman.attack(EntityHuman.java:1022) [patched_1.9.4.jar:git-Paper-773]
    at net.minecraft.server.v1_9_R2.EntityPlayer.attack(EntityPlayer.java:1169) [patched_1.9.4.jar:git-Paper-773]
    at net.minecraft.server.v1_9_R2.PlayerConnection.a(PlayerConnection.java:1614) [patched_1.9.4.jar:git-Paper-773]
    at net.minecraft.server.v1_9_R2.PacketPlayInUseEntity.a(PacketPlayInUseEntity.java:48) [patched_1.9.4.jar:git-Paper-773]
    at net.minecraft.server.v1_9_R2.PacketPlayInUseEntity.a(PacketPlayInUseEntity.java:5) [patched_1.9.4.jar:git-Paper-773]
    at net.minecraft.server.v1_9_R2.PlayerConnectionUtils$1.run(SourceFile:13) [patched_1.9.4.jar:git-Paper-773]
    at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) [?:1.8.0_91]
    at java.util.concurrent.FutureTask.run(Unknown Source) [?:1.8.0_91]
    at net.minecraft.server.v1_9_R2.SystemUtils.a(SourceFile:45) [patched_1.9.4.jar:git-Paper-773]
    at net.minecraft.server.v1_9_R2.MinecraftServer.D(MinecraftServer.java:786) [patched_1.9.4.jar:git-Paper-773]
    at net.minecraft.server.v1_9_R2.DedicatedServer.D(DedicatedServer.java:403) [patched_1.9.4.jar:git-Paper-773]
    at net.minecraft.server.v1_9_R2.MinecraftServer.C(MinecraftServer.java:723) [patched_1.9.4.jar:git-Paper-773]
    at net.minecraft.server.v1_9_R2.MinecraftServer.run(MinecraftServer.java:622) [patched_1.9.4.jar:git-Paper-773]
    at java.lang.Thread.run(Unknown Source) [?:1.8.0_91]
Caused by: java.lang.NullPointerException
    at com.wasteofplastic.askyblock.listeners.IslandGuard.onEntityDamage(IslandGuard.java:1120) ~[?:?]
    at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor516.execute(Unknown Source) ~[?:?]
    at org.bukkit.plugin.EventExecutor$1.execute(EventExecutor.java:44) ~[patched_1.9.4.jar:git-Paper-773]
    ... 25 more

**Comment by tastybento** [comment]
Fixed with 6b50791df124cb679d71d951530f7f1f58f45220
