### ISSUE TITLE
Could not pass event ChallengeCompleteEvent

### ISSUE THREAD

**Issue by Creatif** [tastybento/askyblock#308]
Hello Tasty,

this event seems do not work. :s

```
[16:49:00] [Server thread/ERROR]: Could not pass event ChallengeCompleteEvent to ASkyBlock v3.0.3.2
org.bukkit.event.EventException
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:310) ~[spigot-1.10.2.jar:git-Spigot-078e2f8-21e3b05]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[spigot-1.10.2.jar:git-Spigot-078e2f8-21e3b05]
	at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:502) [spigot-1.10.2.jar:git-Spigot-078e2f8-21e3b05]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:487) [spigot-1.10.2.jar:git-Spigot-078e2f8-21e3b05]
	at com.wasteofplastic.askyblock.commands.Challenges.giveReward(Challenges.java:373) [askyblock.jar:?]
	at com.wasteofplastic.askyblock.commands.Challenges.onCommand(Challenges.java:200) [askyblock.jar:?]
	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44) [spigot-1.10.2.jar:git-Spigot-078e2f8-21e3b05]
	at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:141) [spigot-1.10.2.jar:git-Spigot-078e2f8-21e3b05]
	at org.bukkit.craftbukkit.v1_10_R1.CraftServer.dispatchCommand(CraftServer.java:646) [spigot-1.10.2.jar:git-Spigot-078e2f8-21e3b05]
	at org.bukkit.craftbukkit.v1_10_R1.entity.CraftPlayer.performCommand(CraftPlayer.java:243) [spigot-1.10.2.jar:git-Spigot-078e2f8-21e3b05]
	at com.wasteofplastic.askyblock.panels.ControlPanel.onInventoryClick(ControlPanel.java:278) [askyblock.jar:?]
	at sun.reflect.GeneratedMethodAccessor238.invoke(Unknown Source) ~[?:?]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_72]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_72]
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306) [spigot-1.10.2.jar:git-Spigot-078e2f8-21e3b05]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) [spigot-1.10.2.jar:git-Spigot-078e2f8-21e3b05]
	at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:502) [spigot-1.10.2.jar:git-Spigot-078e2f8-21e3b05]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:487) [spigot-1.10.2.jar:git-Spigot-078e2f8-21e3b05]
	at net.minecraft.server.v1_10_R1.PlayerConnection.a(PlayerConnection.java:1854) [spigot-1.10.2.jar:git-Spigot-078e2f8-21e3b05]
	at net.minecraft.server.v1_10_R1.PacketPlayInWindowClick.a(SourceFile:33) [spigot-1.10.2.jar:git-Spigot-078e2f8-21e3b05]
	at net.minecraft.server.v1_10_R1.PacketPlayInWindowClick.a(SourceFile:10) [spigot-1.10.2.jar:git-Spigot-078e2f8-21e3b05]
	at net.minecraft.server.v1_10_R1.PlayerConnectionUtils$1.run(SourceFile:13) [spigot-1.10.2.jar:git-Spigot-078e2f8-21e3b05]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_72]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_72]
	at net.minecraft.server.v1_10_R1.SystemUtils.a(SourceFile:45) [spigot-1.10.2.jar:git-Spigot-078e2f8-21e3b05]
	at net.minecraft.server.v1_10_R1.MinecraftServer.D(MinecraftServer.java:732) [spigot-1.10.2.jar:git-Spigot-078e2f8-21e3b05]
	at net.minecraft.server.v1_10_R1.DedicatedServer.D(DedicatedServer.java:400) [spigot-1.10.2.jar:git-Spigot-078e2f8-21e3b05]
	at net.minecraft.server.v1_10_R1.MinecraftServer.C(MinecraftServer.java:668) [spigot-1.10.2.jar:git-Spigot-078e2f8-21e3b05]
	at net.minecraft.server.v1_10_R1.MinecraftServer.run(MinecraftServer.java:567) [spigot-1.10.2.jar:git-Spigot-078e2f8-21e3b05]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_72]
Caused by: java.lang.NoSuchMethodError: com.wasteofplastic.askyblock.ASkyBlockAPI.getChallengeStatus(Ljava/util/UUID;)Ljava/util/HashMap;
	at com.github.games647.scoreboardstats.variables.defaults.ASkyBlockVariables.onChallengeComplete(ASkyBlockVariables.java:72) ~[?:?]
	at sun.reflect.GeneratedMethodAccessor556.invoke(Unknown Source) ~[?:?]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_72]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_72]
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306) ~[spigot-1.10.2.jar:git-Spigot-078e2f8-21e3b05]
	... 29 more
```

Crea

**Comment by Steev93** [comment]
@Creatif 
What were you trying to do at the time ?

**Comment by Creatif** [comment]
i found my mystack, sry ;)
