### ISSUE TITLE
Task #78 for ASkyBlock v3.0.3.2 generated an exception

### ISSUE THREAD

**Issue by L4BORG** [tastybento/askyblock#316]
```
>ver ASkyBlock
[00:50:31 INFO]: ASkyBlock version 3.0.3.2
[00:50:31 INFO]: A SkyBlock Plugin
[00:50:31 INFO]: Author: Tastybento
```

```
>ver
[00:52:20 INFO]: This server is running CraftBukkit version git-TacoSpigot-"65fd35f" (MC: 1.8.8) (Implementing API version 1.8.8-R0.2-SNAPSHOT)
[00:52:20 INFO]: Checking version, please wait...
[00:52:21 INFO]: You are running the latest version
```

```
[09:39:53] [Server thread/WARN]: [ASkyBlock] Task #78 for ASkyBlock v3.0.3.2 generated an exception
java.lang.ClassCastException: org.bukkit.craftbukkit.v1_8_R3.entity.CraftGhast cannot be cast to org.bukkit.entity.Creature
	at com.wasteofplastic.askyblock.listeners.FlyingMobEvents$1.run(FlyingMobEvents.java:74) ~[?:?]
	at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftTask.run(CraftTask.java:59) ~[patched.jar:git-TacoSpigot-"65fd35f"]
	at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:349) [patched.jar:git-TacoSpigot-"65fd35f"]
	at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:783) [patched.jar:git-TacoSpigot-"65fd35f"]
	at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:378) [patched.jar:git-TacoSpigot-"65fd35f"]
	at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:713) [patched.jar:git-TacoSpigot-"65fd35f"]
	at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:616) [patched.jar:git-TacoSpigot-"65fd35f"]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_102]
```

**Comment by tastybento** [comment]
Thanks!
Fixed with c58346c
Updated the build 3.0.3.3 pre-release.
