### ISSUE TITLE
NPE InventoryClickEvent (v3.0.3.3)

### ISSUE THREAD

**Issue by L4BORG** [tastybento/askyblock#343]
```
[01:29:48] [Server thread/ERROR]: Could not pass event InventoryClickEvent to ASkyBlock v3.0.3.3
org.bukkit.event.EventException
    at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:302) ~[patched.jar:git-TacoSpigot-"65fd35f"]
    at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:74) ~[patched.jar:git-TacoSpigot-"65fd35f"]
    at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[patched.jar:git-TacoSpigot-"65fd35f"]
    at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:501) [patched.jar:git-TacoSpigot-"65fd35f"]
    at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:486) [patched.jar:git-TacoSpigot-"65fd35f"]
    at net.minecraft.server.v1_8_R3.PlayerConnection.a(PlayerConnection.java:1662) [patched.jar:git-TacoSpigot-"65fd35f"]
    at net.minecraft.server.v1_8_R3.PacketPlayInWindowClick.a(SourceFile:31) [patched.jar:git-TacoSpigot-"65fd35f"]
    at net.minecraft.server.v1_8_R3.PacketPlayInWindowClick.a(SourceFile:9) [patched.jar:git-TacoSpigot-"65fd35f"]
    at net.minecraft.server.v1_8_R3.PlayerConnectionUtils$1.run(SourceFile:13) [patched.jar:git-TacoSpigot-"65fd35f"]
    at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_111]
    at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_111]
    at net.minecraft.server.v1_8_R3.SystemUtils.a(SourceFile:44) [patched.jar:git-TacoSpigot-"65fd35f"]
    at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:774) [patched.jar:git-TacoSpigot-"65fd35f"]
    at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:378) [patched.jar:git-TacoSpigot-"65fd35f"]
    at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:713) [patched.jar:git-TacoSpigot-"65fd35f"]
    at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:616) [patched.jar:git-TacoSpigot-"65fd35f"]
    at java.lang.Thread.run(Thread.java:745) [?:1.8.0_111]
Caused by: org.bukkit.command.CommandException: Unhandled exception executing command 'asc' in plugin ASkyBlock v3.0.3.3
    at org.bukkit.command.PluginCommand.execute(PluginCommand.java:47) ~[patched.jar:git-TacoSpigot-"65fd35f"]
    at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:143) ~[patched.jar:git-TacoSpigot-"65fd35f"]
    at org.bukkit.craftbukkit.v1_8_R3.CraftServer.dispatchCommand(CraftServer.java:666) ~[patched.jar:git-TacoSpigot-"65fd35f"]
    at org.bukkit.craftbukkit.v1_8_R3.entity.CraftPlayer.performCommand(CraftPlayer.java:339) ~[patched.jar:git-TacoSpigot-"65fd35f"]
    at com.wasteofplastic.askyblock.panels.ControlPanel.onInventoryClick(ControlPanel.java:285) ~[?:?]
    at sun.reflect.GeneratedMethodAccessor284.invoke(Unknown Source) ~[?:?]
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_111]
    at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_111]
    at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:300) ~[patched.jar:git-TacoSpigot-"65fd35f"]
    ... 16 more
Caused by: java.lang.NullPointerException
    at com.wasteofplastic.askyblock.commands.Challenges.hasRequired(Challenges.java:1200) ~[?:?]
    at com.wasteofplastic.askyblock.commands.Challenges.checkIfCanCompleteChallenge(Challenges.java:829) ~[?:?]
    at com.wasteofplastic.askyblock.commands.Challenges.onCommand(Challenges.java:199) ~[?:?]
    at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45) ~[patched.jar:git-TacoSpigot-"65fd35f"]
    at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:143) ~[patched.jar:git-TacoSpigot-"65fd35f"]
    at org.bukkit.craftbukkit.v1_8_R3.CraftServer.dispatchCommand(CraftServer.java:666) ~[patched.jar:git-TacoSpigot-"65fd35f"]
    at org.bukkit.craftbukkit.v1_8_R3.entity.CraftPlayer.performCommand(CraftPlayer.java:339) ~[patched.jar:git-TacoSpigot-"65fd35f"]
    at com.wasteofplastic.askyblock.panels.ControlPanel.onInventoryClick(ControlPanel.java:285) ~[?:?]
    at sun.reflect.GeneratedMethodAccessor284.invoke(Unknown Source) ~[?:?]
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_111]
    at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_111]
    at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:300) ~[patched.jar:git-TacoSpigot-"65fd35f"]
    ... 16 more
```

challenges.yml:
http://pastebin.com/nq5GRaxD (default)

**Comment by tastybento** [comment]
Which challenge was being done?

**Comment by L4BORG** [comment]
No idea, there were like 70 players online, however some players did report that they were unable to do alchemist challenge but I'm not sure if that was the case.

**Comment by tastybento** [comment]
So, the error is being created by a potion in the player's inventory that does not have a known name (according to Bukkit). I have added extra code to avoid a NPE like this error, but I'd be interested to know what caused this error. Do you have any special/custom potions or water bottles on your server?

**Comment by L4BORG** [comment]
We had some issues with our builders, if they could spawn this kind of stuff with GM1 and hacked client? Other than that I can't really think of anything...

```
Plugins (32): ServerManager, SimpleTrading, HealthBar, OpenInv, PlugMan, BuycraftX, Votifier, FastAsyncWorldEdit, VoteListener, ViaVersion, Vault, WorldEdit, Essentials, LogBlock, TrailGUI, SilkSpawners, ProtocolLib, WorldGuard, NoCheatPlus, AuctionHouse, ASkyBlock, LockettePro, NoCheatEnforcer, EchoPet, PlayerVaults, UserManager, EssentialsSpawn, ChestShop, CombatTagPlus, CaptureTheArena, HolographicDisplays, CrateReloaded
```

**Comment by tastybento** [comment]
Well, I think the best thing is to just try and avoid the error. I've made a commit 5e4cf3204a84ad181218138934420262a7db773c to do it and it will be in the next release. Thanks.
