### ISSUE TITLE
NPE when animals or mobs spawn outside island boundaries

### ISSUE THREAD

**Issue by tastybento** [tastybento/askyblock#394]
```
Could not pass event CreatureSpawnEvent to ASkyBlock v3.0.5
org.bukkit.event.EventException
at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:310) ~[craftbukkit.jar:git-Spigot-db6de12-18fbb24]
at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[craftbukkit.jar:git-Spigot-db6de12-18fbb24]
at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:502) [craftbukkit.jar:git-Spigot-db6de12-18fbb24]
at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:487) [craftbukkit.jar:git-Spigot-db6de12-18fbb24]
at org.bukkit.craftbukkit.v1_8_R3.event.CraftEventFactory.callCreatureSpawnEvent(CraftEventFactory.java:277) [craftbukkit.jar:git-Spigot-db6de12-18fbb24]
at net.minecraft.server.v1_8_R3.World.addEntity(World.java:1015) [craftbukkit.jar:git-Spigot-db6de12-18fbb24]
at net.minecraft.server.v1_8_R3.EntityOcelot.prepare(EntityOcelot.java:240) [craftbukkit.jar:git-Spigot-db6de12-18fbb24]
at net.minecraft.server.v1_8_R3.SpawnerCreature.a(SpawnerCreature.java:179) [craftbukkit.jar:git-Spigot-db6de12-18fbb24]
at net.minecraft.server.v1_8_R3.WorldServer.doTick(WorldServer.java:227) [craftbukkit.jar:git-Spigot-db6de12-18fbb24]
at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:770) [craftbukkit.jar:git-Spigot-db6de12-18fbb24]
at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:374) [craftbukkit.jar:git-Spigot-db6de12-18fbb24]
at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:654) [craftbukkit.jar:git-Spigot-db6de12-18fbb24]
at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:557) [craftbukkit.jar:git-Spigot-db6de12-18fbb24]
at java.lang.Thread.run(Unknown Source) [?:1.8.0_111]
Caused by: java.lang.NullPointerException
at com.wasteofplastic.askyblock.listeners.IslandGuard.onAnimalSpawn(IslandGuard.java:548) ~[?:?]
at sun.reflect.GeneratedMethodAccessor27.invoke(Unknown Source) ~[?:?]
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_111]
at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_111]
at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306) ~[craftbukkit.jar:git-Spigot-db6de12-18fbb24]
... 13 more
```

**Comment by tastybento** [comment]
Fixed with aff948a.
