### ISSUE TITLE
Could not pass event PlayerInteractEvent to ASkyBlock v3.0.5.2

### ISSUE THREAD

**Issue by L4BORG** [tastybento/askyblock#424]
```
[06:11:33] [Server thread/ERROR]: Could not pass event PlayerInteractEvent to ASkyBlock v3.0.5.2
org.bukkit.event.EventException
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:302) ~[patched.jar:git-TacoSpigot-"65fd35f"]
	at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:74) ~[patched.jar:git-TacoSpigot-"65fd35f"]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[patched.jar:git-TacoSpigot-"65fd35f"]
	at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:501) [patched.jar:git-TacoSpigot-"65fd35f"]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:486) [patched.jar:git-TacoSpigot-"65fd35f"]
	at org.bukkit.craftbukkit.v1_8_R3.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:228) [patched.jar:git-TacoSpigot-"65fd35f"]
	at org.bukkit.craftbukkit.v1_8_R3.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:195) [patched.jar:git-TacoSpigot-"65fd35f"]
	at net.minecraft.server.v1_8_R3.PlayerInteractManager.a(PlayerInteractManager.java:107) [patched.jar:git-TacoSpigot-"65fd35f"]
	at net.minecraft.server.v1_8_R3.PlayerConnection.a(PlayerConnection.java:626) [patched.jar:git-TacoSpigot-"65fd35f"]
	at net.minecraft.server.v1_8_R3.PacketPlayInBlockDig.a(SourceFile:40) [patched.jar:git-TacoSpigot-"65fd35f"]
	at net.minecraft.server.v1_8_R3.PacketPlayInBlockDig.a(SourceFile:10) [patched.jar:git-TacoSpigot-"65fd35f"]
	at net.minecraft.server.v1_8_R3.PlayerConnectionUtils$1.run(SourceFile:13) [patched.jar:git-TacoSpigot-"65fd35f"]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_111]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_111]
	at net.minecraft.server.v1_8_R3.SystemUtils.a(SourceFile:44) [patched.jar:git-TacoSpigot-"65fd35f"]
	at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:774) [patched.jar:git-TacoSpigot-"65fd35f"]
	at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:378) [patched.jar:git-TacoSpigot-"65fd35f"]
	at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:713) [patched.jar:git-TacoSpigot-"65fd35f"]
	at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:616) [patched.jar:git-TacoSpigot-"65fd35f"]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_111]
Caused by: java.lang.IllegalStateException: Start block missed in BlockIterator
	at org.bukkit.util.BlockIterator.<init>(BlockIterator.java:170) ~[patched.jar:git-TacoSpigot-"65fd35f"]
	at org.bukkit.util.BlockIterator.<init>(BlockIterator.java:233) ~[patched.jar:git-TacoSpigot-"65fd35f"]
	at org.bukkit.util.BlockIterator.<init>(BlockIterator.java:268) ~[patched.jar:git-TacoSpigot-"65fd35f"]
	at com.wasteofplastic.askyblock.listeners.IslandGuard.onPlayerInteract(IslandGuard.java:1819) ~[?:?]
	at sun.reflect.GeneratedMethodAccessor177.invoke(Unknown Source) ~[?:?]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_111]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_111]
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:300) ~[patched.jar:git-TacoSpigot-"65fd35f"]
	... 19 more
```

**Comment by tastybento** [comment]
Looks like a bug in your server - it's bugging out in the block iterator method. It's related to the fire protection. You may not be able to use that setting with that old code.

**Comment by L4BORG** [comment]
Hm, so this would mean fire protection is bugged on 1.8.8? (we're running latest TacoSpigot 1.8.8).

**Comment by tastybento** [comment]
Does this happen all the time? What triggers it? I just tested with TacoSpigot 1.8.8 (d/l from GitHub) and it works okay when a visitor punches fire. This line where the error is would be called anytime a player clicks on a block, so it'd be good to know why this is happening.

**Comment by tastybento** [comment]
Closing for now.

**Comment by L4BORG** [comment]
Oh, sorry for not responding. With latest ASkyBlock we don't see this issue anymore (we also updated some other plugins like NoCheatPlus so I'm not quite sure what caused this).
