### ISSUE TITLE
/island minishop gives an internal error

### ISSUE THREAD

**Issue by DudeMcRocks** [tastybento/askyblock#429]
When I do the command /island minishop as an op it says "an internal error occurred while attempting to preform this command"

The console said this
[21:03:56 ERROR]: null
org.bukkit.command.CommandException: Unhandled exception executing command 'island' in plugin ASkyBlock v3.0.5.2
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:46) ~[craftbukkit-1.11.jar:git-Bukkit-c8ff651]
        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:140) ~[craftbukkit-1.11.jar:git-Bukkit-c8ff651]
        at org.bukkit.craftbukkit.v1_11_R1.CraftServer.dispatchCommand(CraftServer.java:628) ~[craftbukkit-1.11.jar:git-Bukkit-c8ff651]
        at net.minecraft.server.v1_11_R1.PlayerConnection.handleCommand(PlayerConnection.java:1278) [craftbukkit-1.11.jar:git-Bukkit-c8ff651]
        at net.minecraft.server.v1_11_R1.PlayerConnection.a(PlayerConnection.java:1138) [craftbukkit-1.11.jar:git-Bukkit-c8ff651]
        at net.minecraft.server.v1_11_R1.PacketPlayInChat.a(SourceFile:37) [craftbukkit-1.11.jar:git-Bukkit-c8ff651]
        at net.minecraft.server.v1_11_R1.PacketPlayInChat.a(SourceFile:9) [craftbukkit-1.11.jar:git-Bukkit-c8ff651]
        at net.minecraft.server.v1_11_R1.PlayerConnectionUtils$1.run(SourceFile:13) [craftbukkit-1.11.jar:git-Bukkit-c8ff651]
        at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) [?:1.8.0_111]
        at java.util.concurrent.FutureTask.run(Unknown Source) [?:1.8.0_111]
        at net.minecraft.server.v1_11_R1.SystemUtils.a(SourceFile:46) [craftbukkit-1.11.jar:git-Bukkit-c8ff651]
        at net.minecraft.server.v1_11_R1.MinecraftServer.D(MinecraftServer.java:695) [craftbukkit-1.11.jar:git-Bukkit-c8ff651]
        at net.minecraft.server.v1_11_R1.DedicatedServer.D(DedicatedServer.java:360) [craftbukkit-1.11.jar:git-Bukkit-c8ff651]
        at net.minecraft.server.v1_11_R1.MinecraftServer.C(MinecraftServer.java:650) [craftbukkit-1.11.jar:git-Bukkit-c8ff651]
        at net.minecraft.server.v1_11_R1.MinecraftServer.run(MinecraftServer.java:554) [craftbukkit-1.11.jar:git-Bukkit-c8ff651]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_111]
Caused by: java.lang.NullPointerException
        at org.bukkit.craftbukkit.v1_11_R1.entity.CraftHumanEntity.openInventory(CraftHumanEntity.java:185) ~[craftbukkit-1.11.jar:git-Bukkit-c8ff651]
        at com.wasteofplastic.askyblock.commands.IslandCmd.onCommand(IslandCmd.java:1422) ~[?:?]
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44) ~[craftbukkit-1.11.jar:git-Bukkit-c8ff651]
        ... 15 more

**Comment by tastybento** [comment]
I suspect there are more errors on the plugin loading in the console. The minishop could not load correctly, so it doesn't exist, so when you try to use it, it doesn't work. Did you edit minishop.yml? There's probably a YAML error in the file. Check it with a YAML syntax checker.

**Comment by DudeMcRocks** [comment]
I have edited the minishop YAML however after checking it with "http://codebeautify.org/yaml-validator" it says its valid. I haven't changed the name or title either.  

I put the entire file in a paste bin.
http://pastebin.com/AsnqB1Vs

**Comment by tastybento** [comment]
Hmm, I just tried it and it works okay. Are you on the latest build of spigot - 1.11.2? Also, do you have an economy plugin installed, like Essentials?

**Comment by tastybento** [comment]
Closing for now.
