### ISSUE TITLE
java.lang.IllegalArgumentException: Cannot set to an empty path

### ISSUE THREAD

**Issue by tastybento** [tastybento/askyblock#473]
https://www.spigotmc.org/threads/a-skyblock.30325/page-168#post-2181134

```
own]
        ... 15 more
[00:32:43 INFO]: starwarzrox logged in with entity id 329 at ([islands] 2796.2, 120.0, -3596.6)
[00:32:43 WARN]: [ASkyBlock] Task #512 for ASkyBlock v3.0.5.4 generated an exception
java.lang.IllegalArgumentException: Cannot set to an empty path
        at org.apache.commons.lang.Validate.notEmpty(Validate.java:321) ~[spigot.jar:git-PistonSpigot-unknown]
        at org.bukkit.configuration.MemorySection.set(MemorySection.java:163) ~[spigot.jar:git-PistonSpigot-unknown]
        at org.bukkit.configuration.MemorySection.set(MemorySection.java:193) ~[spigot.jar:git-PistonSpigot-unknown]
        at com.wasteofplastic.askyblock.Players.save(Players.java:259) ~[?:?]
        at com.wasteofplastic.askyblock.PlayerCache.save(PlayerCache.java:473) ~[?:?]
        at com.wasteofplastic.askyblock.LevelCalcByChunk$1$1.run(LevelCalcByChunk.java:383) ~[?:?]
        at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftTask.run(CraftTask.java:59) ~[spigot.jar:git-PistonSpigot-unknown]
        at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:349) [spigot.jar:git-PistonSpigot-unknown]
        at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:817) [spigot.jar:git-PistonSpigot-unknown]
        at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:398) [spigot.jar:git-PistonSpigot-unknown]
        at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:751) [spigot.jar:git-PistonSpigot-unknown]
        at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:653) [spigot.jar:git-PistonSpigot-unknown]
        at java.lang.Thread.run(Thread.java:744) [?:1.8.0]
 ```

**Comment by tastybento** [comment]
Admin posted challenges.yml that passes YAML syntax checking.

https://hastebin.com/raw/enicazeqam

```
##########################################################################################
# Challenges
# Rewards and required items have to be described using Bukkit Materials
# and be exactly correct
# Do not use Type Id's - they will not work
# Challenges can be one of three types - inventory, island or level.
# inventory - means the player must have the items on them
# island - means the items have to be on the island and within 10 blocks of the player
#          entities are also supported, e.g., COW.
# level - means the island level has to be equal or over this amount.
#         If level is set as nothing '', then the challenge is a free challenge and can be
#         done at any time.
# Challenges can be repeatable only if they are inventory challenges
# permissions can be given as a reward
#
# Reward Commands - commands can be run when a challenge is completed and repeated
# Commands are:
#    rewardcommands:
#      - command1
#      - command2
#    repeatrewardcommands:
#      - command1
#      - command2      
# The commands are listed and run in order. Do not put a / in front of the command.
# The token [player] will be replaced with the player's name.
# Example:
#    rewardcommands:
#      - pex promote [player]
#      - heal [player]
#      - warp winner_circle [player]
# If a command fails, it will be noted in the console.
#
# The format for POTIONS is as follows:
#
# Format POTION:NAME:<LEVEL>:<EXTENDED>:<SPLASH/LINGER>:QTY
# LEVEL, EXTENDED, SPLASH, LINGER are optional.
# LEVEL is a number, 1 or 2
# LINGER is for V1.9 servers and later
# Examples:
# POTION:STRENGTH:1:EXTENDED:SPLASH:1
# POTION:INSTANT_DAMAGE:2::LINGER:2
# POTION:JUMP:2:NOTEXTENDED:NOSPLASH:1
# POTION:WEAKNESS::::1   -  any weakness potion
# 
# Valid potion names are:
# WATER, REGEN, SPEED, FIRE_RESISTANCE, POISON, INSTANT_HEAL, NIGHT_VISION, WEAKNESS,
# STRENGTH, SLOWNESS, JUMP, INSTANT_DAMAGE, WATER_BREATHING, INVISIBILITY
# For V1.9 these are also available:
# LUCK, MUNDANE, THICK, AWKWARD
#
#
# Reseting islands and challenges - usually challenges are reset when a player resets
# their island (see resetchallenges in config.yml). You can stop some challenges from
# being reset by using resetallowed:false in the challenge.
##########################################################################################

challenges:
  # Challenge levels - list as many as you like. If a challenge's level is '' it can
  # be done anytime. You cannot name a challenge the same as a level.
  levels: ''
    
  # The number of undone tasks that can be left on a level before unlocking next level
  waiveramount: 1
  
  # Free levels - which levels above should be auto done when reached, therefore unlocking next level.
  # Example:
  # freelevels: 'Novice' will immediately put player onto Competent level challenges 
  # freelevels: 'Novice Competent' will make all Novice, Competent and Expert challenges available immediately.
  # freelevels: 'Competent' will open Competent and Expert levels once Novice is complete
  freelevels: ''
  
  # This section determines what happens when a player unlocks a new level
  # The subname should correspond to the levels listed above
  # Note that there is no section for the first level as it is automatically unlocked
  levelUnlock:

  # Challenge list
  # Challenge names must be in lowercase. Do not use the same name as a level!
  challengeList:
    onelevelatatimeone:
      friendlyname: 'One Level at a Time I'
      description: 'Reach Island Level 50'
      icon: BOOK
      level: ''
      type: level
      requiredItems: 50
      takeItems: false
      itemReward: 'DIRT:5'
      rewardText: '$500'
      moneyReward: 500
      expReward: 0
      permissionReward: ''
      repeatable: false
      repeatItemReward: ''
      repeatRewardText: ''
      repeatMoneyReward: 0
      repeatExpReward: 0
      #maxtimes: 100
    onelevelatatimetwo:
      friendlyname: 'One Level at a Time II'
      description: 'Reach Island Level 100'
      icon: BOOK
      level: ''
      type: level
      requiredItems: 150
      takeItems: false
      itemReward: 'DIRT:5'
      rewardText: '$1,000'
      moneyReward: 1000
      expReward: 0
      permissionReward: ''
      repeatable: false
      repeatItemReward: ''
      repeatRewardText: ''
      repeatMoneyReward: 0
      repeatExpReward: 0
      #maxtimes: 100
    onelevelatatimethree:
      friendlyname: 'One Level at a Time III'
      description: 'Reach Island Level 250'
      icon: BOOK
      level: ''
      type: level
      requiredItems: 250
      takeItems: false
      itemReward: 'DIRT:5'
      rewardText: '$2,500'
      moneyReward: 2500
      expReward: 0
      permissionReward: ''
      repeatable: false
      repeatItemReward: ''
      repeatRewardText: ''
      repeatMoneyReward: 0
      repeatExpReward: 0
      #maxtimes: 100
    onelevelatatimefour:
      friendlyname: 'One Level at a Time IV'
      description: 'Reach Island Level 500'
      icon: BOOK
      level: ''
      type: level
      requiredItems: 500
      takeItems: false
      itemReward: 'DIRT:5'
      rewardText: '$5,000'
      moneyReward: 5000
      expReward: 0
      permissionReward: ''
      repeatable: false
      repeatItemReward: ''
      repeatRewardText: ''
      repeatMoneyReward: 0
      repeatExpReward: 0
      #maxtimes: 100
    onelevelatatimefive:
      friendlyname: 'One Level at a Time V'
      description: 'Reach Island Level 1000'
      icon: BOOK
      level: ''
      type: level
      requiredItems: 1000
      takeItems: false
      itemReward: ''
      rewardText: '1x Crate Key'
      moneyReward: 25000
      rewardcommands:
      - cr givekey [player] crate 1
      expReward: 0
      permissionReward: ''
      repeatable: false
      repeatItemReward: ''
      repeatRewardText: ''
      repeatMoneyReward: 0
      repeatExpReward: 0
      #maxtimes: 100
    cobblestonecollector:
      friendlyname: 'Cobblestone Collector'
      description: 'Obtain 64x Cobblestone'
      icon: COBBLESTONE
      level: ''
      type: inventory
      requiredItems: 'cobblestone:64' 
      takeItems: true
      rewardText: '$500'
      itemReward: ''
      moneyReward: 500
      expReward: 0
      #rewardcommands:
      #- cr givekey [player] crate 1
      #- cr givekey [player] godlycrate 1
      permissionReward: ''
      repeatable: false
      repeatItemReward: ''
      repeatRewardText: ''
      repeatMoneyReward: 0
      repeatExpReward: 0
      #maxtimes: 100
    grasscollector:
      friendlyname: 'Grass Collector'
      description: 'Obtain 64x Grass'
      icon: GRASS
      level: ''
      type: inventory
      requiredItems: 'grass:64' 
      takeItems: true
      rewardText: '$500'
      itemReward: ''
      moneyReward: 500
      expReward: 0
      #rewardcommands:
      #- cr givekey [player] crate 1
      #- cr givekey [player] godlycrate 1
      permissionReward: ''
      repeatable: false
      repeatItemReward: ''
      repeatRewardText: ''
      repeatMoneyReward: 0
      repeatExpReward: 0
      #maxtimes: 100
    itslit:
      friendlyname: 'Its Lit'
      description: 'Own 5x Beacons on your Island'
      icon: BEACON
      level: ''
      type: island
      requiredItems: 'beacon:5' 
      takeItems: false
      rewardText: '$5,000 & 1x Crate Key'
      itemReward: ''
      moneyReward: 5000
      expReward: 0
      rewardcommands:
      - cr givekey [player] crate 1
      #- cr givekey [player] godlycrate 1
      permissionReward: ''
      repeatable: false
      repeatItemReward: ''
      repeatRewardText: ''
      repeatMoneyReward: 0
      repeatExpReward: 0
      #maxtimes: 100
    myfirstspawner:
      friendlyname: 'My 1st Spawner'
      description: 'Own Any 1x Spawner'
      icon: MOB_SPAWNER
      level: ''
      type: island
      requiredItems: 'mob_spawner:1' 
      takeItems: false
      rewardText: '$1,000 & 1x Crate Key'
      itemReward: ''
      moneyReward: 1000
      expReward: 0
      rewardcommands:
      - cr givekey [player] crate 1
      #- cr givekey [player] godlycrate 1
      permissionReward: ''
      repeatable: false
      repeatItemReward: ''
      repeatRewardText: ''
      repeatMoneyReward: 0
      repeatExpReward: 0
      #maxtimes: 100
    hoppercrazyone:
      friendlyname: 'Hopper Crazy I'
      description: 'Have 32x Hoppers on your Island'
      icon: HOPPER
      level: ''
      type: island
      searchRadius: 25
      requiredItems: 'hopper:32' 
      takeItems: false
      rewardText: '$2,500'
      itemReward: ''
      moneyReward: 2500
      expReward: 0
      #rewardcommands:
      #- cr givekey [player] crate 1
      #- cr givekey [player] godlycrate 1
      permissionReward: ''
      repeatable: false
      repeatItemReward: ''
      repeatRewardText: ''
      repeatMoneyReward: 0
      repeatExpReward: 0
      #maxtimes: 100
    hoppercrazytwo:
      friendlyname: 'Hopper Crazy II'
      description: 'Have 64x Hoppers on your Island'
      icon: HOPPER
      level: ''
      type: island
      searchRadius: 25
      requiredItems: 'hopper:64' 
      takeItems: false
      rewardText: '$5,000'
      itemReward: ''
      moneyReward: 5000
      expReward: 0
      #rewardcommands:
      #- cr givekey [player] crate 1
      #- cr givekey [player] godlycrate 1
      permissionReward: ''
      repeatable: false
      repeatItemReward: ''
      repeatRewardText: ''
      repeatMoneyReward: 0
      repeatExpReward: 0
      #maxtimes: 100
    hoppercrazythree:
      friendlyname: 'Hopper Crazy III'
      description: 'Have 128x Hoppers on your Island'
      icon: HOPPER
      level: ''
      type: island
      searchRadius: 25
      requiredItems: 'hopper:128' 
      takeItems: false
      rewardText: '$10,000'
      itemReward: ''
      moneyReward: 10000
      expReward: 0
      #rewardcommands:
      #- cr givekey [player] crate 1
      #- cr givekey [player] godlycrate 1
      permissionReward: ''
      repeatable: false
      repeatItemReward: ''
      repeatRewardText: ''
      repeatMoneyReward: 0
      repeatExpReward: 0
      #maxtimes: 100
    hoppercrazyfour:
      friendlyname: 'Hopper Crazy IV'
      description: 'Have 256x Hoppers on your Island'
      icon: HOPPER
      level: ''
      type: island
      searchRadius: 25
      requiredItems: 'hopper:256' 
      takeItems: false
      rewardText: '$15,000'
      itemReward: ''
      moneyReward: 15000
      expReward: 0
      #rewardcommands:
      #- cr givekey [player] crate 1
      #- cr givekey [player] godlycrate 1
      permissionReward: ''
      repeatable: false
      repeatItemReward: ''
      repeatRewardText: ''
      repeatMoneyReward: 0
      repeatExpReward: 0
      #maxtimes: 100
    hoppercrazyfive:
      friendlyname: 'Hopper Crazy V'
      description: 'Have 512x Hoppers on your Island'
      icon: HOPPER
      level: ''
      type: island
      searchRadius: 25
      requiredItems: 'hopper:512' 
      takeItems: false
      rewardText: '1x Spawner & 1x Crate Key'
      itemReward: ''
      moneyReward: 0
      expReward: 0
      rewardcommands:
      - cr givekey [player] crate 1
      - ss add [player] cow 1
      permissionReward: ''
      repeatable: false
      repeatItemReward: ''
      repeatRewardText: ''
      repeatMoneyReward: 0
      repeatExpReward: 0
      #maxtimes: 100
    protectyourselfone:
      friendlyname: 'Protect Yourself I'
      description: 'Obtain 1x Set of Leather Armour'
      icon: LEATHER_CHESTPLATE
      level: ''
      type: inventory
      requiredItems: 'leather_helmet:1 leather_chestplate:1 leather_leggings:1 leather_boots:1' 
      takeItems: true
      rewardText: '$750'
      itemReward: ''
      moneyReward: 750
      expReward: 0
      #rewardcommands:
      #- cr givekey [player] crate 1
      #- cr givekey [player] godlycrate 1
      permissionReward: ''
      repeatable: false
      repeatItemReward: ''
      repeatRewardText: ''
      repeatMoneyReward: 0
      repeatExpReward: 0
      #maxtimes: 100
    protectyourselftwo:
      friendlyname: 'Protect Yourself II'
      description: 'Obtain 1x Set of Iron Armour'
      icon: IRON_CHESTPLATE
      level: ''
      type: inventory
      requiredItems: 'iron_helmet:1 iron_chestplate:1 iron_leggings:1 iron_boots:1' 
      takeItems: true
      rewardText: '$1,250'
      itemReward: ''
      moneyReward: 1250
      expReward: 0
      #rewardcommands:
      #- cr givekey [player] crate 1
      #- cr givekey [player] godlycrate 1
      permissionReward: ''
      repeatable: false
      repeatItemReward: ''
      repeatRewardText: ''
      repeatMoneyReward: 0
      repeatExpReward: 0
      #maxtimes: 100
    protectyourselfthree:
      friendlyname: 'Protect Yourself III'
      description: 'Obtain 1x Set of Diamond Armour'
      icon: DIAMOND_CHESTPLATE
      level: ''
      type: inventory
      requiredItems: 'diamond_helmet:1 diamond_chestplate:1 diamond_leggings:1 diamond_boots:1' 
      takeItems: true
      rewardText: '$2,500'
      itemReward: ''
      moneyReward: 2500
      expReward: 0
      #rewardcommands:
      #- cr givekey [player] crate 1
      #- cr givekey [player] godlycrate 1
      permissionReward: ''
      repeatable: false
      repeatItemReward: ''
      repeatRewardText: ''
      repeatMoneyReward: 0
      repeatExpReward: 0
      #maxtimes: 100
    abitprickly:
      friendlyname: 'A Bit Prickly'
      description: 'Obtain 1,000x Cactus'
      icon: CACTUS
      type: inventory
      level: ''
      requiredItems: 'cactus:1000' 
      takeItems: true
      rewardText: '$1,000'
      itemReward: ''
      moneyReward: 1000
      expReward: 0
      #rewardcommands:
      #- cr givekey [player] crate 1
      #- cr givekey [player] godlycrate 1
      permissionReward: ''
      repeatable: false
      repeatItemReward: ''
      repeatRewardText: ''
      repeatMoneyReward: 0
      repeatExpReward: 0
      #maxtimes: 100
    dollarbillsone:
      friendlyname: 'Dollar Bills I'
      description: 'Have 32x Diamond Blocks on your Island'
      icon: DIAMOND_BLOCK
      level: ''
      type: island
      requiredItems: 'diamond_block:32' 
      takeItems: true
      rewardText: '$1,000'
      itemReward: ''
      moneyReward: 1000
      expReward: 0
      #rewardcommands:
      #- cr givekey [player] crate 1
      #- cr givekey [player] godlycrate 1
      permissionReward: ''
      repeatable: false
      repeatItemReward: ''
      repeatRewardText: ''
      repeatMoneyReward: 0
      repeatExpReward: 0
      #maxtimes: 100
    dollarbillstwo:
      friendlyname: 'Dollar Bills II'
      description: 'Have 64x Diamond Blocks on your Island'
      icon: DIAMOND_BLOCK
      level: ''
      type: island
      requiredItems: 'diamond_block:64' 
      takeItems: true
      rewardText: '$5,000'
      itemReward: ''
      moneyReward: 5000
      expReward: 0
      #rewardcommands:
      #- cr givekey [player] crate 1
      #- cr givekey [player] godlycrate 1
      permissionReward: ''
      repeatable: false
      repeatItemReward: ''
      repeatRewardText: ''
      repeatMoneyReward: 0
      repeatExpReward: 0
      #maxtimes: 100
    dollarbillsthree:
      friendlyname: 'Dollar Bills III'
      description: 'Have 128x Diamond Blocks on your Island'
      icon: DIAMOND_BLOCK
      level: ''
      type: island
      requiredItems: 'diamond_block:128' 
      takeItems: true
      rewardText: '$10,000'
      itemReward: '$10,000 & 1x Crate Key'
      moneyReward: 10000
      expReward: 0
      rewardcommands:
      - cr givekey [player] crate 1
      #- cr givekey [player] godlycrate 1
      permissionReward: ''
      repeatable: false
      repeatItemReward: ''
      repeatRewardText: ''
      repeatMoneyReward: 0
      repeatExpReward: 0
      #maxtimes: 100
    fishermanone:
      friendlyname: 'Fisherman I'
      description: 'Catch & Cook 16x Fish'
      icon: COOKED_FISH
      level: ''
      type: inventory
      requiredItems: 'cooked_fish:16' 
      takeItems: true
      rewardText: '$1,000'
      itemReward: ''
      moneyReward: 1000
      expReward: 0
      #rewardcommands:
      #- cr givekey [player] crate 1
      #- cr givekey [player] godlycrate 1
      permissionReward: ''
      repeatable: false
      repeatItemReward: ''
      repeatRewardText: ''
      repeatMoneyReward: 0
      repeatExpReward: 0
      #maxtimes: 100
    fishermantwo:
      friendlyname: 'Fisherman II'
      description: 'Catch & Cook 32x Fish'
      icon: COOKED_FISH
      level: ''
      type: inventory
      requiredItems: 'cooked_fish:16' 
      takeItems: true
      rewardText: '$2,000'
      itemReward: ''
      moneyReward: 2000
      expReward: 0
      #rewardcommands:
      #- cr givekey [player] crate 1
      #- cr givekey [player] godlycrate 1
      permissionReward: ''
      repeatable: false
      repeatItemReward: ''
      repeatRewardText: ''
      repeatMoneyReward: 0
      repeatExpReward: 0
      #maxtimes: 100
    fishermanthree:
      friendlyname: 'Fisherman III'
      description: 'Catch & Cook 64x Fish'
      icon: COOKED_FISH
      level: ''
      type: inventory
      requiredItems: 'cooked_fish:64' 
      takeItems: true
      rewardText: '$3,000'
      itemReward: ''
      moneyReward: 3000
      expReward: 0
      #rewardcommands:
      #- cr givekey [player] crate 1
      #- cr givekey [player] godlycrate 1
      permissionReward: ''
      repeatable: false
      repeatItemReward: ''
      repeatRewardText: ''
      repeatMoneyReward: 0
      repeatExpReward: 0
      #maxtimes: 100
    cowlover:
      friendlyname: 'Cow Lover'
      description: 'Obtain a Cow Spawner'
      icon: COOKED_BEEF
      level: ''
      type: island
      requiredItems: 'mob_spawner:1:92' 
      takeItems: false
      rewardText: '$25,000 & 1x Crate Key'
      itemReward: ''
      moneyReward: 25000
      expReward: 0
      rewardcommands:
      - cr givekey [player] crate 1
      #- cr givekey [player] godlycrate 1
      permissionReward: ''
      repeatable: false
      repeatItemReward: ''
      repeatRewardText: ''
      repeatMoneyReward: 0
      repeatExpReward: 0
      #maxtimes: 100
    cowgrinder:
      friendlyname: 'Cow Grinder I'
      description: 'Have 100x Cows on your Island'
      icon: COOKED_BEEF
      level: ''
      type: island
      requiredItems: 'cow:100' 
      takeItems: false
      rewardText: '$5,000 & 1x Crate Key'
      itemReward: ''
      moneyReward: 5000
      expReward: 0
      rewardcommands:
      - cr givekey [player] crate 1
      #- cr givekey [player] godlycrate 1
      permissionReward: ''
      repeatable: false
      repeatItemReward: ''
      repeatRewardText: ''
      repeatMoneyReward: 0
      repeatExpReward: 0
      #maxtimes: 100
    cowgrinder2:
      friendlyname: 'Cow Grinder II'
      description: 'Have 250x Cows on your Island'
      icon: COOKED_BEEF
      level: ''
      type: island
      requiredItems: 'cow:250' 
      takeItems: false
      rewardText: '$15,000 & 1x Crate Key'
      itemReward: ''
      moneyReward: 10000
      expReward: 0
      rewardcommands:
      - cr givekey [player] crate 1
      #- cr givekey [player] godlycrate 1
      permissionReward: ''
      repeatable: false
      repeatItemReward: ''
      repeatRewardText: ''
      repeatMoneyReward: 0
      repeatExpReward: 0
      #maxtimes: 100
    irongolemlover:
      friendlyname: 'Iron Golem Lover'
      description: 'Obtain 1x Iron Golem Spawner'
      icon: IRON_INGOT
      level: ''
      type: island
      requiredItems: 'mob_spawner:1:99' 
      takeItems: false
      rewardText: '$5,000 & 1x Crate Key'
      itemReward: ''
      moneyReward: 5000
      expReward: 0
      rewardcommands:
      - cr givekey [player] crate 1
      #- cr givekey [player] godlycrate 1
      permissionReward: ''
      repeatable: false
      repeatItemReward: ''
      repeatRewardText: ''
      repeatMoneyReward: 0
      repeatExpReward: 0
      #maxtimes: 100
    irongolemgrinder:
      friendlyname: 'Iron Golem Grinder I'
      description: 'Have 100x Iron Golems on your Island'
      icon: IRON_INGOT
      level: ''
      type: island
      requiredItems: 'iron_golem:100' 
      takeItems: false
      rewardText: '$5,000 & 1x Crate Key'
      itemReward: ''
      moneyReward: 5000
      expReward: 0
      rewardcommands:
      - cr givekey [player] crate 1
      #- cr givekey [player] godlycrate 1
      permissionReward: ''
      repeatable: false
      repeatItemReward: ''
      repeatRewardText: ''
      repeatMoneyReward: 0
      repeatExpReward: 0
      #maxtimes: 100
    irongolemgrinder2:
      friendlyname: 'Iron Golem Grinder II'
      description: 'Have 250x Iron Golems on your Island'
      icon: IRON_INGOT
      level: ''
      type: island
      requiredItems: 'iron_golem:100' 
      takeItems: false
      rewardText: '$10,000 & 1x Crate Key'
      itemReward: ''
      moneyReward: 10000
      expReward: 0
      rewardcommands:
      - cr givekey [player] crate 1
      #- cr givekey [player] godlycrate 1
      permissionReward: ''
      repeatable: false
      repeatItemReward: ''
      repeatRewardText: ''
      repeatMoneyReward: 0
      repeatExpReward: 0
      #maxtimes: 100
    homesweethome:
      friendlyname: 'Home Sweet Home'
      description: 'Build a house that contains at least 1 Wooden Door, Bed, Bookshelf, Crafting Table, Furnace, Glass Window, and Torch.'
      icon: BED
      level: ''
      type: island
      requiredItems: 'BED_BLOCK:1 WORKBENCH:1 GLASS:1 WOODEN_DOOR:1 FURNACE:1 BOOKSHELF:1 TORCH:1'
      takeItems: false
      itemReward: 'JUKEBOX:1 RECORD_12:1'
      rewardText: '1 Jukebox & 1 Music Disk'
      moneyReward: 0
      expReward: 0
      permissionReward: ''
      repeatable: false
      repeatItemReward: ''
      repeatRewardText: ''
      repeatMoneyReward: 0
      repeatExpReward: 0
    tothenether:
      friendlyname: 'To the Nether!'
      description: 'Build a Nether Portal on your Island and activate it.'
      icon: NETHERRACK
      level: ''
      type: island
      requiredItems: 'OBSIDIAN:10 PORTAL:1'
      takeItems: false
      itemReward: 'DIAMOND_SWORD:1'
      rewardText: '1x Diamond Sword & $500'
      moneyReward: 500
      expReward: 0
      permissionReward: ''
      repeatable: false
      repeatItemReward: ''
      repeatRewardText: ''
      repeatMoneyReward: 0
      repeatExpReward: 0
    alchemist:
      friendlyname: 'Alchemist'
      description: 'Brew 1 potion of Fire Resistance, Slowness, Swiftness, Healing, Harming, Invisibility, Strength and Regeneration'
      icon: BREWING_STAND_ITEM
      level: ''
      type: inventory
      requiredItems: 'POTION:FIRE_RESISTANCE::::1 POTION:SLOWNESS::::1 POTION:SPEED::::1 POTION:INSTANT_HEAL::::1 POTION:INSTANT_DAMAGE::::1 POTION:INVISIBILITY::::1 POTION:STRENGTH::::1 POTION:REGEN::::1'
      takeItems: true
      itemReward: 'ENCHANTMENT_TABLE:1'
      rewardText: '1x Enchantment Table'
      moneyReward: 0
      expReward: 0
      permissionReward: ''
      repeatable: false
      repeatItemReward: 'DIAMOND:1'
      repeatRewardText: '1 diamond'
      repeatMoneyReward: 20
      repeatExpReward: 20
    partyone:
      friendlyname: "It's a Party"
      description: 'Have a party! Invite 4 friends.'
      icon: SKULL_ITEM
      level: ''
      type: island
      requiredItems: 'PLAYER:5'
      takeItems: false
      itemReward: 'PUMPKIN_PIE:6'
      rewardText: '6x Pumpkin Pies & $1,000'
      moneyReward: 1000
      expReward: 0
      permissionReward: ''
      repeatable: false
      repeatItemReward: ''
      repeatRewardText: ''
      repeatMoneyReward: 0
      repeatExpReward: 0
    farmer:
      description: 'Harvest 64x of the following: Wheat, Sugar, Melon, Carrots, Potatoes & Pumpkin'
      icon: WHEAT
      level: ''
      type: inventory
      requiredItems: 'WHEAT:64 SUGAR:64 MELON:64 CARROT_ITEM:64 POTATO_ITEM:64 PUMPKIN:64'
      takeItems: true
      itemReward: 'MONSTER_EGG:PIG:2 MONSTER_EGG:COW:2 MONSTER_EGG:CHICKEN:2'
      rewardText: '2x Spawn Egg (Chicken, Cow & Pig) & 100 XP'
      moneyReward: 0
      expReward: 100
      permissionReward: ''
      repeatable: false
      repeatItemReward: 'MONSTER_EGG:PIG:2 MONSTER_EGG:COW:2 MONSTER_EGG:CHICKEN:2'
      repeatRewardText: '1 cocoa bean, 1 spawn egg(chicken,cow,pig)'
      repeatMoneyReward: 20
      repeatExpReward: 20
      # Max times limits how many times a challenge can be done. Comment out to make unlimited
      maxtimes: 100
    cobbleking:
      friendlyname: 'The Cobble Carrier '
      description: 'Obtain 2,000x Cobble in your Inventory'
      icon: COBBLESTONE
      level: ''
      type: inventory
      requiredItems: 'COBBLESTONE:2000'
      takeItems: true
      itemReward: 'STONE:512'
      permissionReward: ''
      rewardText: '512x Stone, $1,250 & 250XP'
      moneyReward: 1250
      expReward: 250
      repeatable: false
      repeatItemReward: 'LEATHER:1'
      repeatRewardText: '1 leather'
      repeatMoneyReward: 5
      repeatExpReward: 10
      # Max times limits how many times a challenge can be done. Comment out to make unlimited
```

**Comment by tastybento** [comment]
**Issue replicated**. Logging into server with the challenges.yml causes an immediate console error. Here is the full error:
```
[15:58:52 INFO]: UUID of player tastybento is 5988eecd-1dcd-4080-a843-785b62419abb
[15:58:52 ERROR]: Could not pass event PlayerJoinEvent to ASkyBlock v3.0.5.4
org.bukkit.event.EventException
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306) ~[spigot-1.11.2.jar:git-Spigot-7d78b81-775f1e1]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[spigot-1.11.2.jar:git-Spigot-7d78b81-775f1e1]
	at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:502) [spigot-1.11.2.jar:git-Spigot-7d78b81-775f1e1]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:487) [spigot-1.11.2.jar:git-Spigot-7d78b81-775f1e1]
	at net.minecraft.server.v1_11_R1.PlayerList.onPlayerJoin(PlayerList.java:327) [spigot-1.11.2.jar:git-Spigot-7d78b81-775f1e1]
	at net.minecraft.server.v1_11_R1.PlayerList.a(PlayerList.java:160) [spigot-1.11.2.jar:git-Spigot-7d78b81-775f1e1]
	at net.minecraft.server.v1_11_R1.LoginListener.b(LoginListener.java:147) [spigot-1.11.2.jar:git-Spigot-7d78b81-775f1e1]
	at net.minecraft.server.v1_11_R1.LoginListener.F_(LoginListener.java:57) [spigot-1.11.2.jar:git-Spigot-7d78b81-775f1e1]
	at net.minecraft.server.v1_11_R1.NetworkManager.a(NetworkManager.java:233) [spigot-1.11.2.jar:git-Spigot-7d78b81-775f1e1]
	at net.minecraft.server.v1_11_R1.ServerConnection.c(ServerConnection.java:140) [spigot-1.11.2.jar:git-Spigot-7d78b81-775f1e1]
	at net.minecraft.server.v1_11_R1.MinecraftServer.D(MinecraftServer.java:834) [spigot-1.11.2.jar:git-Spigot-7d78b81-775f1e1]
	at net.minecraft.server.v1_11_R1.DedicatedServer.D(DedicatedServer.java:399) [spigot-1.11.2.jar:git-Spigot-7d78b81-775f1e1]
	at net.minecraft.server.v1_11_R1.MinecraftServer.C(MinecraftServer.java:675) [spigot-1.11.2.jar:git-Spigot-7d78b81-775f1e1]
	at net.minecraft.server.v1_11_R1.MinecraftServer.run(MinecraftServer.java:574) [spigot-1.11.2.jar:git-Spigot-7d78b81-775f1e1]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_111]
Caused by: java.lang.IllegalArgumentException: Cannot set to an empty path
	at org.apache.commons.lang.Validate.notEmpty(Validate.java:321) ~[spigot-1.11.2.jar:git-Spigot-7d78b81-775f1e1]
	at org.bukkit.configuration.MemorySection.set(MemorySection.java:167) ~[spigot-1.11.2.jar:git-Spigot-7d78b81-775f1e1]
	at org.bukkit.configuration.MemorySection.set(MemorySection.java:201) ~[spigot-1.11.2.jar:git-Spigot-7d78b81-775f1e1]
	at com.wasteofplastic.askyblock.Players.save(Players.java:259) ~[?:?]
	at com.wasteofplastic.askyblock.PlayerCache.save(PlayerCache.java:473) ~[?:?]
	at com.wasteofplastic.askyblock.listeners.JoinLeaveEvents.onPlayerJoin(JoinLeaveEvents.java:299) ~[?:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_111]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_111]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_111]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_111]
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:302) ~[spigot-1.11.2.jar:git-Spigot-7d78b81-775f1e1]
	... 14 more
[15:58:53 INFO]: tastybento[/127.0.0.1:51360] logged in with entity id 53 at ([ASkyBlock]0.9268801759890306, 118.0, 0.724829888112118)
```

**Comment by tastybento** [comment]
Issue present on 3.0.6 and current release.

**Comment by tastybento** [comment]
Caused by '' as the levels. Edge case - never designed to have no levels. Added a no level check.

**Comment by Poslovitch** [comment]
Added in to do list for the rewrite to make sure it'll continue to handle this case
