### ISSUE TITLE
island generration error with react plugin.

### ISSUE THREAD

**Issue by NCSV** [tastybento/askyblock#514]
Please read below explanation.

I experience some errors when I try to generate some islands with the Askyblock Plugin & the React Plugin.
(React Plugin is similar to the ClearLagg Plugin.)
I am currently using spigot-1.8.8-R0.1-SNAPSHOT build on my server. When I set the distance between the islands as over 200 blocks, I receive this message: An internal error occured while attempting to perfomr this command Also, same error happens when I create an island with a setting of 200 distance, 100 protection area, and 70 heights.
I asked the React Plugin forum about this issue but could not receive a proper solution. With the Askyblock island & the React Plugin,
generating up to the 2nd user's island was working fine, but I was not able to generate the 3rd island properly due to the error
It was working fine once I re-initialized the Askyblock Plugin after removing the React Plugin.
But I would like to run both plugin without error if possible.

Following is the link to the
React Plugin: https://www.spigotmc.org/resources/react-smart-server-performance.21057/
Please review this issue and aid me if possible. Thanks!

----------------------------

Here's a error :
org.bukkit.command.CommandException: Unhandled exception executing command 'is' in plugin ASkyBlock v3.0.5.4
at org.bukkit.command.PluginCommand.execute(PluginCommand.java:46) ~[craftbukkit.jar:git-Spigot-db6de12-18fbb24]
at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:141) ~[craftbukkit.jar:git-Spigot-db6de12-18fbb24]
at org.bukkit.craftbukkit.v1_8_R3.CraftServer.dispatchCommand(CraftServer.java:641) ~[craftbukkit.jar:git-Spigot-db6de12-18fbb24]
at net.minecraft.server.v1_8_R3.PlayerConnection.handleCommand(PlayerConnection.java:1162) [craftbukkit.jar:git-Spigot-db6de12-18fbb24]
at net.minecraft.server.v1_8_R3.PlayerConnection.a(PlayerConnection.java:997) [craftbukkit.jar:git-Spigot-db6de12-18fbb24]
at net.minecraft.server.v1_8_R3.PacketPlayInChat.a(PacketPlayInChat.java:45) [craftbukkit.jar:git-Spigot-db6de12-18fbb24]
at net.minecraft.server.v1_8_R3.PacketPlayInChat.a(PacketPlayInChat.java:1) [craftbukkit.jar:git-Spigot-db6de12-18fbb24]
at net.minecraft.server.v1_8_R3.PlayerConnectionUtils$1.run(SourceFile:13) [craftbukkit.jar:git-Spigot-db6de12-18fbb24]
at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) [?:1.8.0_121]
at java.util.concurrent.FutureTask.run(Unknown Source) [?:1.8.0_121]
at net.minecraft.server.v1_8_R3.SystemUtils.a(SourceFile:44) [craftbukkit.jar:git-Spigot-db6de12-18fbb24]
at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:715) [craftbukkit.jar:git-Spigot-db6de12-18fbb24]
at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:374) [craftbukkit.jar:git-Spigot-db6de12-18fbb24]
at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:654) [craftbukkit.jar:git-Spigot-db6de12-18fbb24]
at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:557) [craftbukkit.jar:git-Spigot-db6de12-18fbb24]
at java.lang.Thread.run(Unknown Source) [?:1.8.0_121]
Caused by: java.lang.ClassCastException: org.bukkit.craftbukkit.v1_8_R3.block.CraftBlockState cannot be cast to org.bukkit.block.Chest
at com.wasteofplastic.askyblock.schematics.IslandBlock.paste(IslandBlock.java:565) ~[?:?]
at com.wasteofplastic.askyblock.schematics.Schematic.pasteSchematic(Schematic.java:780) ~[?:?]
at com.wasteofplastic.askyblock.commands.IslandCmd.newIsland(IslandCmd.java:713) ~[?:?]
at com.wasteofplastic.askyblock.commands.IslandCmd.chooseIsland(IslandCmd.java:3045) ~[?:?]
at com.wasteofplastic.askyblock.commands.IslandCmd.onCommand(IslandCmd.java:1155) ~[?:?]
at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44) ~[craftbukkit.jar:git-Spigot-db6de12-18fbb24]
... 15 more

**Comment by tastybento** [comment]
This error should not occur in 3.0.6 because code was added to avoid it. However, I'm not sure why this happens on the 3rd island like you say. Please check out 3.0.6 when it comes out (or test the beta version). (Commit da5ad05).

**Comment by tastybento** [comment]
Here's the pre-release:
https://github.com/tastybento/askyblock/releases/tag/v3.0.6-rc
