### ISSUE TITLE
island generration error with react plugin / 2

### ISSUE THREAD

**Issue by NCSV** [tastybento/askyblock#521]
First, sorry for my English. I'm not good at English. Please comprehend.

I issued bug about island generation error with react plugin before.
Link:
https://github.com/tastybento/askyblock/issues/514

And you gave me a pre-release version. So I apply it follow the manual.
Plugin loaded correctly but still the same problem. 

----
And I think island level settings don't work. I was setting 70 but still generated Y120.

**Comment by tastybento** [comment]
Please paste the error you see. Are you using 3.0.6? 

For the height - provide a copy of your config.yml using pastebin.com

**Comment by tastybento** [comment]
Thanks for the bug report - I've fixed the island height issue.

**Comment by NCSV** [comment]
[10:58:43] [Server thread/ERROR]: null
org.bukkit.command.CommandException: Unhandled exception executing command 'is' in plugin ASkyBlock v3.0.6
	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:46) ~[craftbukkit.jar:git-Spigot-db6de12-18fbb24]
	at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:141) ~[craftbukkit.jar:git-Spigot-db6de12-18fbb24]
	at org.bukkit.craftbukkit.v1_8_R3.CraftServer.dispatchCommand(CraftServer.java:641) ~[craftbukkit.jar:git-Spigot-db6de12-18fbb24]
	at net.minecraft.server.v1_8_R3.PlayerConnection.handleCommand(PlayerConnection.java:1162) [craftbukkit.jar:git-Spigot-db6de12-18fbb24]
	at net.minecraft.server.v1_8_R3.PlayerConnection.a(PlayerConnection.java:997) [craftbukkit.jar:git-Spigot-db6de12-18fbb24]
	at net.minecraft.server.v1_8_R3.PacketPlayInChat.a(PacketPlayInChat.java:45) [craftbukkit.jar:git-Spigot-db6de12-18fbb24]
	at net.minecraft.server.v1_8_R3.PacketPlayInChat.a(PacketPlayInChat.java:1) [craftbukkit.jar:git-Spigot-db6de12-18fbb24]
	at net.minecraft.server.v1_8_R3.PlayerConnectionUtils$1.run(SourceFile:13) [craftbukkit.jar:git-Spigot-db6de12-18fbb24]
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) [?:1.8.0_121]
	at java.util.concurrent.FutureTask.run(Unknown Source) [?:1.8.0_121]
	at net.minecraft.server.v1_8_R3.SystemUtils.a(SourceFile:44) [craftbukkit.jar:git-Spigot-db6de12-18fbb24]
	at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:715) [craftbukkit.jar:git-Spigot-db6de12-18fbb24]
	at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:374) [craftbukkit.jar:git-Spigot-db6de12-18fbb24]
	at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:654) [craftbukkit.jar:git-Spigot-db6de12-18fbb24]
	at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:557) [craftbukkit.jar:git-Spigot-db6de12-18fbb24]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_121]
Caused by: java.lang.ClassCastException: org.bukkit.craftbukkit.v1_8_R3.block.CraftBlockState cannot be cast to org.bukkit.block.Sign
	at com.wasteofplastic.askyblock.schematics.IslandBlock.paste(IslandBlock.java:548) ~[?:?]
	at com.wasteofplastic.askyblock.schematics.Schematic.pasteSchematic(Schematic.java:780) ~[?:?]
	at com.wasteofplastic.askyblock.commands.IslandCmd.newIsland(IslandCmd.java:734) ~[?:?]
	at com.wasteofplastic.askyblock.commands.IslandCmd.newIsland(IslandCmd.java:673) ~[?:?]
	at com.wasteofplastic.askyblock.commands.IslandCmd.chooseIsland(IslandCmd.java:3210) ~[?:?]
	at com.wasteofplastic.askyblock.commands.IslandCmd.onCommand(IslandCmd.java:1179) ~[?:?]
	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44) ~[craftbukkit.jar:git-Spigot-db6de12-18fbb24]
	... 15 more
[10:58:51] [Server thread/INFO]: shakyminicore issued server command: /섬

**Comment by tastybento** [comment]
Please try these two versions with changes:

https://github.com/tastybento/askyblock/releases/tag/3.0.6nms

https://github.com/tastybento/askyblock/releases/tag/3.0.6block

Hopefully, 3.0.6nms will fix the error. But if not, try 3.0.6block.

**Comment by tastybento** [comment]
By the way, I'm away for a week so I may not be able to help until next weekend.

**Comment by tastybento** [comment]
@NCSV Did it work okay?

**Comment by NCSV** [comment]
I tested it. 3.0.6nms build work well.
Thank you for helping.
