### ISSUE TITLE
Error always when players join or quit server

### ISSUE THREAD

**Issue by PhantasiaMC** [tastybento/askyblock#530]
Hi ^^ Excuse me, I get this error in my server each time a player join or leave :(

```
[22:42:21] [Server thread/ERROR]: Could not pass event PlayerQuitEvent to ASkyBlock v3.0.5.4
org.bukkit.event.EventException
at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306) ~[spigotmc-1.11.2-R0.1.jar:git-Spigot-65a0347-a552117]
at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[spigotmc-1.11.2-R0.1.jar:git-Spigot-65a0347-a552117]
at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:502) [spigotmc-1.11.2-R0.1.jar:git-Spigot-65a0347-a552117]
at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:487) [spigotmc-1.11.2-R0.1.jar:git-Spigot-65a0347-a552117]
at net.minecraft.server.v1_11_R1.PlayerList.disconnect(PlayerList.java:379) [spigotmc-1.11.2-R0.1.jar:git-Spigot-65a0347-a552117]
at net.minecraft.server.v1_11_R1.PlayerConnection.a(PlayerConnection.java:1054) [spigotmc-1.11.2-R0.1.jar:git-Spigot-65a0347-a552117]
at net.minecraft.server.v1_11_R1.NetworkManager.handleDisconnection(NetworkManager.java:316) [spigotmc-1.11.2-R0.1.jar:git-Spigot-65a0347-a552117]
at net.minecraft.server.v1_11_R1.ServerConnection.c(ServerConnection.java:174) [spigotmc-1.11.2-R0.1.jar:git-Spigot-65a0347-a552117]
at net.minecraft.server.v1_11_R1.MinecraftServer.D(MinecraftServer.java:842) [spigotmc-1.11.2-R0.1.jar:git-Spigot-65a0347-a552117]
at net.minecraft.server.v1_11_R1.DedicatedServer.D(DedicatedServer.java:399) [spigotmc-1.11.2-R0.1.jar:git-Spigot-65a0347-a552117]
at net.minecraft.server.v1_11_R1.MinecraftServer.C(MinecraftServer.java:678) [spigotmc-1.11.2-R0.1.jar:git-Spigot-65a0347-a552117]
at net.minecraft.server.v1_11_R1.MinecraftServer.run(MinecraftServer.java:576) [spigotmc-1.11.2-R0.1.jar:git-Spigot-65a0347-a552117]
at java.lang.Thread.run(Thread.java:745) [?:1.8.0_112]
Caused by: java.lang.IllegalArgumentException: Cannot set to an empty path
at org.apache.commons.lang.Validate.notEmpty(Validate.java:321) ~[spigotmc-1.11.2-R0.1.jar:git-Spigot-65a0347-a552117]
at org.bukkit.configuration.MemorySection.set(MemorySection.java:167) ~[spigotmc-1.11.2-R0.1.jar:git-Spigot-65a0347-a552117]
at org.bukkit.configuration.MemorySection.set(MemorySection.java:201) ~[spigotmc-1.11.2-R0.1.jar:git-Spigot-65a0347-a552117]
at com.wasteofplastic.askyblock.Players.save(Players.java:259) ~[?:?]
at com.wasteofplastic.askyblock.PlayerCache.removeOnlinePlayer(PlayerCache.java:95) ~[?:?]
at com.wasteofplastic.askyblock.listeners.JoinLeaveEvents.onPlayerQuit(JoinLeaveEvents.java:360) ~[?:?]
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_112]
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_112]
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_112]
at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_112]
at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:302) ~[spigotmc-1.11.2-R0.1.jar:git-Spigot-65a0347-a552117]
... 12 more
```

How can this issue can be fixed please ? Thanks in advance :)

Best regards,

Maxime ^^

**Comment by tastybento** [comment]
This should be fixed in 3.0.6 that is in testing now. Please wait a few days.
