### ISSUE TITLE
schematica issue

### ISSUE THREAD

**Issue by DarkMonolith** [tastybento/askyblock#578]
Gahh, so basically I changed the schematics folder to my custom islands, and now all the plugin outputs is '/island help' when I type /is

Im running 1.11.2

[22:06:48] [Server thread/ERROR]: Error occurred while enabling ASkyBlock v3.0.6 (Is it up to date?)
java.lang.NullPointerException
at com.wasteofplastic.askyblock.schematics.Schematic.<init>(Schematic.java:389) ~[?:?]
at com.wasteofplastic.askyblock.commands.IslandCmd.loadSchematics(IslandCmd.java:173) ~[?:?]
at com.wasteofplastic.askyblock.commands.IslandCmd.<init>(IslandCmd.java:130) ~[?:?]
at com.wasteofplastic.askyblock.ASkyBlock.onEnable(ASkyBlock.java:326) ~[?:?]
at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:271) ~[craftbukkit.jar:git-Bukkit-cf05ccc]
at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:329) [craftbukkit.jar:git-Bukkit-cf05ccc]
at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:404) [craftbukkit.jar:git-Bukkit-cf05ccc]
at org.bukkit.craftbukkit.v1_11_R1.CraftServer.enablePlugin(CraftServer.java:361) [craftbukkit.jar:git-Bukkit-cf05ccc]
at org.bukkit.craftbukkit.v1_11_R1.CraftServer.enablePlugins(CraftServer.java:323) [craftbukkit.jar:git-Bukkit-cf05ccc]
at org.bukkit.craftbukkit.v1_11_R1.CraftServer.<init>(CraftServer.java:261) [craftbukkit.jar:git-Bukkit-cf05ccc]
at net.minecraft.server.v1_11_R1.PlayerList.<init>(PlayerList.java:73) [craftbukkit.jar:git-Bukkit-cf05ccc]
at net.minecraft.server.v1_11_R1.DedicatedPlayerList.<init>(SourceFile:14) [craftbukkit.jar:git-Bukkit-cf05ccc]
at net.minecraft.server.v1_11_R1.DedicatedServer.init(DedicatedServer.java:185) [craftbukkit.jar:git-Bukkit-cf05ccc]
at net.minecraft.server.v1_11_R1.MinecraftServer.run(MinecraftServer.java:521) [craftbukkit.jar:git-Bukkit-cf05ccc]
at java.lang.Thread.run(Unknown Source) [?:1.8.0_91]

**Comment by tastybento** [comment]
The problem is with the schematic. Please share it with me via dropbox.com or some other way so I can test it and find the problem. What plugin did you use to make it?

**Comment by Poslovitch** [comment]
This issue was moved to tastybento/ASkyBlock-Bugs-N-Features#13

**Comment by DarkMonolith** [comment]
I used schematica mod. When I use WE it works fine. I guess Schematica has some issues with it
