### ISSUE TITLE
Hey i have Error

### ISSUE THREAD

**Issue by DzGNico** [tastybento/askyblock#595]
`[14:59:42 INFO]: DzG_Nico issued server command: /challenge
[14:59:42 ERROR]: null
org.bukkit.command.CommandException: Unhandled exception executing command 'challenge' in plugin ASkyBlock v3.0.6
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:46) ~[PluginCommand.class:1.7.10-1614.58]
        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:181) ~[SimpleCommandMap.class:1.7.10-1614.58]
        at org.bukkit.craftbukkit.v1_7_R4.CraftServer.dispatchCommand(CraftServer.java:740) ~[CraftServer.class:1.7.10-1614.58]
        at net.minecraft.network.NetHandlerPlayServer.func_147361_d(NetHandlerPlayServer.java:1370) [nh.class:?]
        at net.minecraft.network.NetHandlerPlayServer.func_147354_a(NetHandlerPlayServer.java:1107) [nh.class:?]
        at net.minecraft.network.play.client.C01PacketChatMessage.func_148833_a(C01PacketChatMessage.java:38) [ir.class:?]
        at net.minecraft.network.play.client.C01PacketChatMessage.func_148833_a(C01PacketChatMessage.java:53) [ir.class:?]
        at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:245) [ej.class:?]
        at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:181) [nc.class:?]
        at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:1023) [MinecraftServer.class:?]
        at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:432) [lt.class:?]
        at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:841) [MinecraftServer.class:?]
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:693) [MinecraftServer.class:?]
        at java.lang.Thread.run(Thread.java:745) [?:1.8.0_121]
Caused by: java.lang.NoClassDefFoundError: org/bukkit/inventory/ItemFlag
        at com.wasteofplastic.askyblock.commands.Challenges.createItem(Challenges.java:1819) ~[?:?]
        at com.wasteofplastic.askyblock.commands.Challenges.challengePanel(Challenges.java:1637) ~[?:?]
        at com.wasteofplastic.askyblock.commands.Challenges.challengePanel(Challenges.java:1603) ~[?:?]
        at com.wasteofplastic.askyblock.commands.Challenges.onCommand(Challenges.java:123) ~[?:?]
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44) ~[PluginCommand.class:1.7.10-1614.58]
        ... 13 more`

Sorry for my English I come from Germany

**Comment by Poslovitch** [comment]
@tastybento As I saw, it's due to the ItemFlag we added in 3.0.6 to have a better display for the completed challenges. 

@DzGNico can you please tell us what server version are you using ?

**Comment by DzGNico** [comment]
1.7.10 Because of SkyMod

**Comment by tastybento** [comment]
Fixed by 	15a67b2. Will be in the 3.0.6.1.
