### ISSUE TITLE
Issue with source code.

### ISSUE THREAD

**Issue by TheUpBeatGamer** [tastybento/askyblock#603]
Hello,

I keep getting this error with the source code when I compile it and try run it on the server.

[13:39:40] [Server thread/ERROR]: Error occurred while enabling SkyCore v${version} (Is it up to date?)
java.lang.Error: Unresolved compilation problems: 
	Economy cannot be resolved to a type
	The method getRegistration(Class<Economy>) from the type ServicesManager refers to the missing type Economy
	net.milkbowl cannot be resolved to a type
	Economy cannot be resolved to a type
	Economy cannot be resolved to a type

	at com.wasteofplastic.askyblock.util.VaultHelper.setupEconomy(VaultHelper.java:40) ~[?:?]
	at com.wasteofplastic.askyblock.ASkyBlock.onEnable(ASkyBlock.java:295) ~[?:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:316) ~[spigot.jar:git-PaperSpigot-1f7d532]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:332) [spigot.jar:git-PaperSpigot-1f7d532]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:412) [spigot.jar:git-PaperSpigot-1f7d532]
	at org.bukkit.craftbukkit.v1_7_R4.CraftServer.loadPlugin(CraftServer.java:476) [spigot.jar:git-PaperSpigot-1f7d532]
	at org.bukkit.craftbukkit.v1_7_R4.CraftServer.enablePlugins(CraftServer.java:394) [spigot.jar:git-PaperSpigot-1f7d532]
	at net.minecraft.server.v1_7_R4.DedicatedServer.init(DedicatedServer.java:170) [spigot.jar:git-PaperSpigot-1f7d532]
	at net.minecraft.server.v1_7_R4.MinecraftServer.run(MinecraftServer.java:494) [spigot.jar:git-PaperSpigot-1f7d532]
	at net.minecraft.server.v1_7_R4.ThreadServerApplication.run(SourceFile:628) [spigot.jar:git-PaperSpigot-1f7d532]

**Comment by tastybento** [comment]
Your dependencies are missing in your project. You should try to use Maven because that automatically sets your dependencies.

**Comment by tastybento** [comment]
This issue was moved to tastybento/ASkyBlock-Bugs-N-Features#76
